# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        cache-dependency-path: src/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build

    - name: Copy production fxmanifest to dist folder
      run: cp ../dist.fxmanifest.lua ../dist/fxmanifest.lua

    - name: Copy .gitignore to dist folder
      run: cp ../.gitignore ../dist/.gitignore

    # - name: Copy server and client Lua files to dist folder
    #   run: |
    #     find server -type f -name "*.lua" -exec sh -c 'mkdir -p ../dist/$(dirname "{}") && cp "{}" "../dist/{}"' \;
    #     find server_external -type f -name "*.lua" -exec sh -c 'mkdir -p ../dist/$(dirname "{}") && cp "{}" "../dist/{}"' \;
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: player-info-api
        path: dist
        
